version: '3'
services:
  nats:
    image: "nats:2.1.8-alpine"
  publisher:
    image: nats-fibonacci-publisher
    depends_on:
      - nats
  worker:
    image: nats-fibonacci-worker
    depends_on:
      - nats
